### ISSUE TITLE
ML-DSA new NIST KAT

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [open-quantum-safe/liboqs#1879] opened 2024-08-02 05:28 UTC
Observed that [main](https://github.com/open-quantum-safe/liboqs) branch has implementation which OK against [NIST KAT from Apr 15, 2024](https://github.com/usnistgov/ACVP-Server/blob/eb31c8ef41d1f62177960180c16d6ae8b9fba648/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json).
However there is fresh [NIST KAT from May 23, 2024](https://github.com/usnistgov/ACVP-Server/blob/8b2204159c1b31a3202ff415cc7a9e1058c35fc5/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json) ([KAT history](https://github.com/usnistgov/ACVP-Server/commits/master/gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json)). So need to fix ML-DSA implementation.

**Comment by baentsch** [comment] 2024-08-02 08:03
Looks like a duplicate of #1850, do you agree @UladzimirTrehubenka ? If so, please close this issue and provide additional input there.

**Comment by UladzimirTrehubenka** [comment] 2024-08-02 10:59
Closed as duplicate of https://github.com/open-quantum-safe/liboqs/issues/1850

**Closed** 2024-08-02 10:58 UTC

**Comment by baentsch** [comment] 2024-08-02 11:08
Thanks @UladzimirTrehubenka ! @SWilson4 @bhess fyi...
