### ISSUE TITLE
Compilation error: Cannot open include file: 'dlfcn.h'

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/liboqs#1935] opened 2024-09-26 06:07 UTC
**Describe the bug**
When building for windows on windows with VS19 I get the following compilation error:

```
20:58:05  C:\Users\****local\workspace\422-use-oqs-provider-main-branch\submodules\linphone-sdk\external\liboqs\src\common\ossl_helpers.c(7): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```

**Environment (please complete the following information):**
 - OS: windows, VS 19
 - OpenSSL version: -
 - liboqs version: main

**Comment by pi-314159** [comment] 2024-09-27 04:22
Please also check #1768

**Comment by SWilson4** [comment] 2024-09-27 13:47
Closing as a duplicate of #1768.

**Closed by SWilson4** 2024-09-27 13:47 UTC
