### ISSUE TITLE
Cannot open tmp file for reading when running test_kem_mem and test_sig_mem

### ISSUE THREAD

**Issue by yifanluo2006** [open-quantum-safe/liboqs#1885] opened 2024-08-09 05:30 UTC
**Describe the bug**
When attempting to run test_kem_mem or test_sig_mem encapsulation/sign or decapsulation/verify, an error is returned stating cannot read tmp file for reading. 
**To Reproduce**
1. cd build
2. cd tests
3. ./test_kem_mem BIKE-L1 2 

Note that this apply to any kem or sig algorithm

**Expected behavior**
"Couldn't open tmp/oqs-temp-file-BIKE-L1pk for reading."

**Screenshots**
<img width="1295" alt="Screenshot 2024-08-09 at 1 19 55 PM" src="https://github.com/user-attachments/assets/f0a847f5-f7e7-4c73-a229-57df06b53fff">

**Environment (please complete the following information):**
 - OS: MacOS 15.0, however this problem also exists on Ubuntu
 - OpenSSL version 3.3.1
 - Compiler version used clang (14.0.3 (clang-1403.0.22.14.1))
 - liboqs version main branch

**Additional context**
This can be resolved by writing another script to manually generate and save the tmp files; however, this is rather tedious

**Comment by baentsch** [comment] 2024-08-09 06:19
Thanks for the report, @yifanluo2006 This program has not been designed to be run stand-alone but only within the test harness, more specifically [test_mem.py](https://github.com/open-quantum-safe/liboqs/blob/main/tests/test_mem.py).

If you see a need for it to run independently, please, by all means provide a PR (and accompanying documentation) to improve this -- while maintaining the semantics allowing CI (incl. the above test script) to keep working OK.

**Comment by dstebila** [comment] 2024-09-17 17:26
Closing as this is intended behaviour as noted in https://github.com/open-quantum-safe/liboqs/issues/1885#issuecomment-2277227182.  If change in behaviour is desired, please follow up with a PR to improve.

**Closed by dstebila** 2024-09-17 17:26 UTC
Labels: enhancement
