### ISSUE TITLE
Clear compiler warnings on Windows

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/liboqs#644] opened 2020-03-04 21:18 UTC
As noted in https://github.com/open-quantum-safe/liboqs/pull/633#issuecomment-594024236

**Comment by xvzcf** [comment] 2020-03-17 17:45
I came across [this](https://gitlab.kitware.com/cmake/cmake/issues/19084), which (among other things) says that, when the compiler is MSVC, the generated CMake build files have the `W3` flag automatically added to them. I've also verified that our MSVC 2019 Appveyor Builds do have this flag turned on.

**Comment by christianpaquin** [comment] 2020-03-17 19:18
I've started to look at all the warnings. I've asked for review from the code authors.

**Comment by christianpaquin** [comment] 2020-03-17 21:49
- qtesla warnings are addressed in an upstream commit I need to merge in
 - picnic warnings are safe to ignore; on the picnic's to-do list to address, eventually
 - test warnings are safe to ignore.

I'll modify the code/cmakelists accordingly

**Comment by christianpaquin** [comment] 2020-03-30 19:56
Done in PR #664 and #665.

**Comment by dstebila** [comment] 2020-04-01 00:24
Compiler warnings look clear to me.  Is there a MSVC equivalent of `-Werror` that we should turn on?

There are some warnings during linking -- should we do anything about those?  

```
[00:01:07] [887/898] Linking C executable tests\test_sig.exe
[00:01:07]    Creating library tests\test_sig.lib and object tests\test_sig.exp
[00:01:07] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:07] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:07] [888/898] Linking C executable tests\kat_sig.exe
[00:01:07]    Creating library tests\kat_sig.lib and object tests\kat_sig.exp
[00:01:07] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:07] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:07] [889/898] Building C object tests\CMakeFiles\example_kem.dir\example_kem.c.obj
[00:01:07] [890/898] Building C object tests\CMakeFiles\speed_sig.dir\speed_sig.c.obj
[00:01:08] [891/898] Linking C executable tests\example_sig.exe
[00:01:08]    Creating library tests\example_sig.lib and object tests\example_sig.exp
[00:01:08] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:08] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:08] [892/898] Linking C executable tests\speed_sig.exe
[00:01:08]    Creating library tests\speed_sig.lib and object tests\speed_sig.exp
[00:01:08] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:08] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:08] [893/898] Linking C executable tests\example_kem.exe
[00:01:08]    Creating library tests\example_kem.lib and object tests\example_kem.exp
[00:01:08] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:08] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:08] [894/898] Building C object tests\CMakeFiles\test_kem.dir\test_kem.c.obj
[00:01:08] [895/898] Linking C executable tests\kat_kem.exe
[00:01:08]    Creating library tests\kat_kem.lib and object tests\kat_kem.exp
[00:01:08] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:08] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:09] [896/898] Linking C executable tests\test_kem.exe
[00:01:09]    Creating library tests\test_kem.lib and object tests\test_kem.exp
[00:01:09] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:09] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
[00:01:09] [897/898] Building C object tests\CMakeFiles\speed_kem.dir\speed_kem.c.obj
[00:01:09] [898/898] Linking C executable tests\speed_kem.exe
[00:01:09]    Creating library tests\speed_kem.lib and object tests\speed_kem.exp
[00:01:09] LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
[00:01:09] LINK : warning LNK4217: symbol '_wassert' defined in 'libucrt.lib(assert.obj)' is imported by 'cpu_features.lib(cpuinfo_x86.c.obj)' in function 'ExtractBitRange'
```

**Comment by christianpaquin** [comment] 2020-04-02 17:29
I think `/WX` is the equivalent for `cl.exe`. I'll check the linking warnings.

**Comment by dstebila** [comment] 2020-04-03 17:04
> By the way, where did you see the warnings; local or on AppVeyor? My local cmake compilation doesn't print them out (is there an option to print out warnings?)

https://ci.appveyor.com/project/dstebila/liboqs/builds/31249636/job/934ptnnyt8qa8lvl

**Comment by christianpaquin** [comment] 2020-04-07 14:48
Nothing shows up when I compile locally. Is there a setting in cmake to printout the warnings?

**Comment by dstebila** [comment] 2020-04-07 15:07
Not sure why your output is different than AppVeyor's.  Sorry.

**Comment by christianpaquin** [comment] 2020-04-07 16:50
Ok, I get the warnings now by static library; I'll take a look.

**Comment by christianpaquin** [comment] 2020-04-07 17:40
It looks like the Windows build is linking with the debug C runtime even in non-debug builds; the `/MD` option should be used instead of `/MDd` in this case. It looks like cmake is setting this automatically, I can't find any of our config files specifying this. I wrote some code to correct this in `CMakeLists.txt`:
```
if(WIN32)
     set(CMAKE_GENERATOR_CC cl)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
        set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MDd")
    else()
        set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MD")
    endif()
 endif()
```

It gets rid of the `LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs` warning, but the `/MDd` option still appears all over the build directory.  It looks like it comes from `build/CMakeCache.txt`: 

```
//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1
```

Is the default build debug even if you don't explicitly specify its type to be `Debug`? @dstebila @xvzcf ?

**Comment by xvzcf** [comment] 2020-04-07 17:42
No, the default isn't Debug, and I think CMake is automatically setting it to that. But then again, I've been using `CMAKE_BUILD_TYPE` incorrectly, which I need to fix.

**Comment by christianpaquin** [comment] 2020-04-07 18:39
When I set `CMAKE_BUILD_TYPE=Release` the problem goes away (`/MD` is used instead of `/MDd` as it should be) without any workaround code. So the issue only appears if we don't set the `CMAKE_BUILD_TYPE` explicitly to Debug or Release. `appveyor_build.bat` uses `Optimized`; what should it be instead? (adding Debug/Release, removing Optimized?)

**Comment by xvzcf** [comment] 2020-04-08 13:11
> what should it be instead? (adding Debug/Release, removing Optimized?)

Yup, it should be like that all over, as noted [here](https://github.com/open-quantum-safe/liboqs/issues/695)/

**Comment by christianpaquin** [comment] 2020-04-22 21:46
@xvzcf; following our conversation on the call today, when I configure cmake without any flag (`cmake -GNinja ..`), I still get the `/MDd` flag, which implies debug mode. Is that the expected behavior? Should appveyor build OQS using the `CMAKE_BUILD_TYPE=Release`?

**Comment by xvzcf** [comment] 2020-04-23 14:10
Yup, will be pushing a fix soon.

**Comment by christianpaquin** [comment] 2020-04-24 21:24
Was PR #730 the fix you mentioned, @xvzcf ?

**Comment by xvzcf** [comment] 2020-04-27 13:35
Yup.

**Comment by dstebila** [comment] 2020-04-27 15:18
Did #730 resolve this?

**Comment by christianpaquin** [comment] 2020-04-27 15:59
I think so. Appveyor now builds in Release mode, and the right DLL is used at linking. I don't see the warning locally, nor in the nightly build, so I think this is done.

**Closed** 2020-04-29 18:24 UTC
