### ISSUE TITLE
Update CBOM to CycloneDX 1.6 specification

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/liboqs#1753] opened 2024-04-10 07:20 UTC
The specification used for [CBOMs](https://github.com/open-quantum-safe/liboqs/blob/main/docs/cbom.json) has been upstreamed to CycloneDX 1.6:
https://github.com/CycloneDX/specification/releases/tag/1.6

This issue is to update the CBOM in liboqs, and its generation script to the CycloneDX 1.6 specification.

**Comment by baentsch** [comment] 2024-04-22 15:11
As per https://github.com/open-quantum-safe/liboqs/pull/1708#issuecomment-2069210942 also document CBOM utility, use and development/developer's implications.

**Comment by planetf1** [comment] 2024-07-04 09:36
See also https://github.com/open-quantum-safe/liboqs/issues/1831

I missed this issue when originally opening the above - apologies. I added some observations. We can close one, though I did try to add my non-expert comments. @bhess let me know if you want any help with this.

**Comment by dstebila** [comment] 2024-07-23 14:41
Closing this issue as a dupe of #1831.

**Closed by dstebila** 2024-07-23 14:41 UTC
